"""Initial schema for job_profiles and evaluation_results

Revision ID: 6c46fc90bc73
Revises: 
Create Date: 2026-09-21 18:44:40.103945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c46fc90bc73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_profiles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category_queries', sa.JSON(), nullable=False),
    sa.Column('hard_filter_rules', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.String(length=64), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('category_scores', sa.JSON(), nullable=False),
    sa.Column('verified_citations', sa.JSON(), nullable=False),
    sa.Column('invalid_citations', sa.JSON(), nullable=False),
    sa.Column('has_critical_flags', sa.Boolean(), nullable=False),
    sa.Column('llm_raw_output', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_results')
    op.drop_table('job_profiles')
    # ### end Alembic commands ###
